# Generated by Django 3.0.5 on 2020-04-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200419_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
